import me.champeau.gradle.igp.gitRepositories

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.3/userguide/multi_project_builds.html
 */

pluginManagement {
    repositories {
        //google()
        //jcenter()
        gradlePluginPortal()
    }
}

plugins {
    id("me.champeau.includegit") version "0.1.1"
}

rootProject.name = "rocket-launcher"

include(":rocket-launcher-core")
include(":rocket-launcher-gui")

gitRepositories {
    include("kotlin-fsm") {
        uri.set("https://github.com/funczz/kotlin-fsm.git")
        //branch.set("main")
        tag.set("v0.1.0")
    }
}

gitRepositories {
    include("kotlin-sam") {
        uri.set("https://github.com/funczz/kotlin-sam.git")
        //branch.set("main")
        tag.set("v0.1.0")
    }
}
